# Generated by Django 4.2.3 on 2023-07-11 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], default='student', max_length=10),
        ),
    ]
