# Generated by Django 4.2.3 on 2023-07-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0002_student_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
