# Generated by Django 4.2.3 on 2023-07-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0006_remove_student_views_instructorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorrequest',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
