# Generated by Django 4.2.3 on 2023-07-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0007_instructorrequest_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level_type',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=12),
        ),
    ]
