# Generated by Django 4.2.3 on 2023-07-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0010_instructorrequest_is_rejected'),
        ('eAcademyApp', '0011_alter_course_image'),
    ]

    operations = [
    ]
