# Generated by Django 4.2.3 on 2023-07-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0012_merge_20230723_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='course_images/'),
        ),
    ]
