# Generated by Django 4.2.3 on 2023-07-24 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0015_weeklycontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
