# Generated by Django 4.2.3 on 2023-07-27 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0016_remove_course_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eAcademyApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eAcademyApp.userprofile')),
            ],
        ),
    ]
