# Generated by Django 4.2.3 on 2023-07-27 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0017_studentcourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grade',
        ),
    ]
