# Generated by Django 4.2.3 on 2023-07-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0018_remove_userprofile_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklycontent',
            name='assignment_file',
            field=models.FileField(default='Lec_2_-_Python_Programming_L3gQPaa.pdf', upload_to='weekly_content/assignment/'),
        ),
    ]
