# Generated by Django 4.2.3 on 2023-07-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0019_weeklycontent_assignment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='assignment_answer_file',
            field=models.FileField(blank=True, null=True, upload_to='student_assignment_answers/'),
        ),
    ]
