# Generated by Django 4.2.3 on 2023-07-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0020_studentcourse_assignment_answer_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='assignment_grade',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='weeklycontent',
            name='max_grade',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
