# Generated by Django 4.2.3 on 2023-07-31 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0021_studentcourse_assignment_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='assignment_answer_file',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='assignment_grade',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='studentcourse',
            name='grade',
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_answer_file', models.FileField(blank=True, null=True, upload_to='student_assignment_answers/')),
                ('grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('attendance', models.PositiveIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eAcademyApp.userprofile')),
                ('weekly_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eAcademyApp.weeklycontent')),
            ],
        ),
    ]
