# Generated by Django 4.2.3 on 2023-07-31 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eAcademyApp', '0022_remove_studentcourse_assignment_answer_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCourse',
        ),
    ]
